### ISSUE TITLE
Folders not found

### ISSUE THREAD

**Issue by tejaswini-wq** [AKSW/linked-uspto-patent-data#1]
I was not able to find raw-code-folder,structured-code-folder and missed-code-folder. Can anyone help me.

**Comment by JensLehmann** [comment]
Did you run downloadFiles? ( https://github.com/SmartDataAnalytics/linked-uspto-patent-data/blob/master/scripts/downloadFiles.sh )

**Comment by tejaswini-wq** [comment]
Yes

**Comment by tejaswini-wq** [comment]
> Did you run downloadFiles? ( https://github.com/SmartDataAnalytics/linked-uspto-patent-data/blob/master/scripts/downloadFiles.sh )
